# Generated by Django 5.0.4 on 2024-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HpClockfiyApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('hasUnitPrice', models.BooleanField(default=False)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ExpenseCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('billable', models.BooleanField(default=True)),
                ('fieldId', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField()),
                ('timesheetId', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Expense',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='employeeuser',
            table='EmployeeUser',
        ),
        migrations.AlterModelTable(
            name='entry',
            table='Entry',
        ),
    ]
