# Generated by Django 5.0.4 on 2024-04-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HpClockfiyApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='employeeuser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tagsfor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'managed': True},
        ),
    ]
