# Generated by Django 5.0.4 on 2024-05-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HpClockfiyApi', '0002_category_expense_alter_employeeuser_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackGroundTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(default=404)),
                ('message', models.CharField(max_length=250)),
                ('data', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('caller', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'BackGroundTaskDjango',
                'managed': False,
            },
        ),
    ]
