# Generated by Django 5.0.4 on 2024-07-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HpClockfiyApi', '0003_backgroundtaskresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRep',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ClientRep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EqpRateSheet',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unitRate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('dayRate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'EqpRateSheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipEntry',
            fields=[
                ('id', models.CharField(db_column='_id', max_length=50, primary_key=True, serialize=False)),
                ('isUnitRate', models.BooleanField()),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'EquipEntry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('equipId', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilesForExpense',
            fields=[
                ('expenseId', models.CharField(db_column='expenseId', max_length=64, primary_key=True, serialize=False)),
                ('workspaceId', models.CharField(db_column='workspaceId', max_length=50)),
                ('binaryData', models.TextField(db_column='binaryData')),
            ],
            options={
                'db_table': 'FilesForExpense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LemEntry',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('work', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('travel', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('calc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('meals', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('hotel', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'LemEntry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LemSheet',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lem_sheet_date', models.DateField()),
                ('lemNumber', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LemSheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LemWorker',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'LemWorker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequests',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('policyId', models.CharField(db_column='pID', max_length=50)),
                ('start', models.DateTimeField(db_column='startDate')),
                ('end', models.DateTimeField(db_column='end_date')),
                ('duration', models.FloatField(default=0)),
                ('balanceDiff', models.FloatField(db_column='paidTimeOff', default=0)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TimeOffRequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerRateSheet',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('workRate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('travelRate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('calcRate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'WorkerRateSheet',
                'managed': False,
            },
        ),
    ]
