# Generated by Django 5.0.4 on 2024-07-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HpClockfiyApi', '0004_clientrep_eqpratesheet_equipentry_equipment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipEntry',
        ),
    ]
