# Generated by Django 3.2.25 on 2024-03-28 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('baseRate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryId', models.CharField(max_length=50)),
                ('duration', models.FloatField()),
                ('description', models.TextField()),
                ('billable', models.BooleanField()),
                ('type', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeOffPolicies',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=50)),
                ('accrual_amount', models.FloatField()),
                ('accrual_period', models.CharField(max_length=15)),
                ('time_unit', models.CharField(max_length=14)),
                ('archived', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('approved_time', models.FloatField()),
                ('billable_time', models.FloatField()),
                ('billable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.employeeuser')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TimeOffRequests',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_time_off', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after_request', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.employeeuser')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.timeoffpolicies')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='timeoffpolicies',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.workspace'),
        ),
        migrations.CreateModel(
            name='TagsFor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('timeID', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.entry')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.client')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('holidayID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.usergroups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.employeeuser')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.project'),
        ),
        migrations.AddField(
            model_name='entry',
            name='time_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.timesheet'),
        ),
        migrations.AddField(
            model_name='entry',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.workspace'),
        ),
        migrations.AddField(
            model_name='client',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HpAPI.workspace'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user', 'group', 'workspace'], name='HpAPI_gr_user_id_0441ca_idx'),
        ),
    ]
