# Generated by Django 3.2.25 on 2024-04-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HpAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='employeeuser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='holidays',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tagsfor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='timeoffpolicies',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='timeoffrequests',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usergroups',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'managed': True},
        ),
    ]
