# Generated by Django 2.1.15 on 2024-04-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HpAPI', '0003_auto_20240402_1400'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calendar',
            table='Calendar',
        ),
        migrations.AlterModelTable(
            name='client',
            table='Client',
        ),
        migrations.AlterModelTable(
            name='employeeuser',
            table='EmployeeUser',
        ),
        migrations.AlterModelTable(
            name='entry',
            table='Entry',
        ),
        migrations.AlterModelTable(
            name='groupmembership',
            table='GroupMembership',
        ),
        migrations.AlterModelTable(
            name='holidays',
            table='Holidays',
        ),
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
        migrations.AlterModelTable(
            name='tagsfor',
            table='TagsFor',
        ),
        migrations.AlterModelTable(
            name='timeoffpolicies',
            table='TimeOffPolicies',
        ),
        migrations.AlterModelTable(
            name='timeoffrequests',
            table='TimeOffRequests',
        ),
        migrations.AlterModelTable(
            name='timesheet',
            table='TimeSheet',
        ),
        migrations.AlterModelTable(
            name='usergroups',
            table='UserGroups',
        ),
        migrations.AlterModelTable(
            name='workspace',
            table='Workspace',
        ),
    ]
